### ISSUE TITLE
ConcurrentModificationException while call Bugsnag.notify()

### ISSUE THREAD

**Issue by panser** [bugsnag/bugsnag-java#148]
The same issue as here https://github.com/bugsnag/bugsnag-android/issues/281 , but currently during use `bugsnag-spring`
```
java.util.ConcurrentModificationException        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at com.bugsnag.Bugsnag.notify(Bugsnag.java:447)
        at com.bugsnag.Bugsnag.notify(Bugsnag.java:407)
        at com.bugsnag.Bugsnag.notify(Bugsnag.java:350)
```

**Comment by fractalwrench** [comment]
Thanks for reporting this @panser - a fix for the issue has been shipped in v3.6.1.
