### ISSUE TITLE
Network error when posting to http://notify.bugsnag.com

### ISSUE THREAD

**Issue by peterxuxin** [bugsnag/bugsnag-java#31]
Network error when posting to http://notify.bugsnag.com
public static void main(String[] args)
    {
        Client bugsnag = new Client("my-key");
        LOG.info("HelloWorld start.");
        workerA.start();
        workerB.start();
        bugsnag.notify(new RuntimeException("Non-fatal"));
        int ss = 1998/0;
        LOG.info("HelloWorld end." + ss);
        
    }

**Comment by peterxuxin** [comment]
proxy ??

**Comment by kattrali** [comment]
Hi @peterxuxin, thank you for the report. What is the name and description of the network error? Any details would help with debugging this issue.

**Comment by peterxuxin** [comment]
Access network in our company needs to use the proxy with account and password.
I will try Bugsnag on public network.

**Here is the exception info:**
[Bugsnag] WARNING: Error notifying Bugsnag
com.bugsnag.http.NetworkException: Network error when posting to http://notify.bugsnag.com
	at com.bugsnag.http.HttpClient.post(HttpClient.java:73)
	at com.bugsnag.Notification.deliver(Notification.java:98)
	at com.bugsnag.Client.notify(Client.java:115)
	at com.bugsnag.Client.notify(Client.java:123)
	at com.bugsnag.Client.notify(Client.java:135)
	at com.huawei.bes.helloworld.HelloWorld.main(HelloWorld.java:32)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at com.bugsnag.http.HttpClient.post(HttpClient.java:52)
	... 5 more

**Comment by peterxuxin** [comment]
@kattrali 
It is OK to use bugsnag on public network.

**Comment by kattrali** [comment]
@peterxuxin Thank you for the update! It looks like we need to add proxy support to the library. I will file a separate issue for this specifically.

**Comment by peterxuxin** [comment]
ok

**Comment by kattrali** [comment]
Just merged #33, which will add proxy settings to the next release.
