### ISSUE TITLE
bugsnag nullPointerException issue，any body can help me?

### ISSUE THREAD

**Issue by sunyangnj** [bugsnag/bugsnag-java#37]
Caused by: java.lang.NullPointerException
at com.bugsnag.Error.getExceptionName(Error.java:198)
at com.bugsnag.Error.shouldIgnore(Error.java:96)
at com.bugsnag.Client.notify(Client.java:115)
at com.bugsnag.Client.notify(Client.java:128)
at com.bugsnag.Client.notify(Client.java:136)
at com.huawei.bes.common.log.impl.BesLogImpl.debug(BesLogImpl.java:206)
at com.huawei.bes.common.log.impl.BesLogImpl.debug(BesLogImpl.java:178)
at com.huawei.bes.common.dfx.monitor.BESCustomEBusStatistic.initFilter(BESCustomEBusStatistic.java:86)
at com.huawei.bes.common.dfx.monitor.BESCustomEBusStatistic.init(BESCustomEBusStatistic.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1581)

**Comment by kattrali** [comment]
Hi @sunyangnj, thank you for the report! Could you also provide the error message before the `Caused by` line and your Bugsnag version? Thanks!

**Comment by kattrali** [comment]
I'm releasing an update to potentially fix this, but feel free to reopen if the problem recurs. Thanks!
